services:
  db:
    image: postgres:15
    container_name: portfolio_davirosa_db
    restart: always
    environment:
      POSTGRES_DB: portfolio_davirosa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/portfolio_davirosa
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network: